import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json([
    {
      id: "iphone15",
      name: "iPhone 15",
      brand: "Apple",
      price: 79999,
      rating: 4.6,
      image: "/products/iphone15.jpg",
      category: "mobile",
      battery: "3349mAh",
      camera: "48MP",
      display: "6.1 inch OLED",
      processor: "A16 Bionic",
    },

    {
      id: "s24",
      name: "Samsung S24",
      brand: "Samsung",
      price: 69999,
      rating: 4.5,
      image: "/products/s24.jpg",
      category: "mobile",
      battery: "4000mAh",
      camera: "50MP",
      display: "6.2 inch AMOLED",
      processor: "Snapdragon 8 Gen 3",
    },

    {
      id: "oneplus13",
      name: "OnePlus 13",
      brand: "OnePlus",
      price: 64999,
      rating: 4.7,
      image: "/products/oneplus13.jpg",
      category: "mobile",
      battery: "6000mAh",
      camera: "50MP Triple Camera",
      display: "6.82 inch AMOLED",
      processor: "Snapdragon 8 Elite",
    },

    {
      id: "pixel9",
      name: "Google Pixel 9",
      brand: "Google",
      price: 74999,
      rating: 4.6,
      image: "/products/pixel9.jpg",
      category: "mobile",
      battery: "4700mAh",
      camera: "50MP",
      display: "6.3 inch OLED",
      processor: "Google Tensor G4",
    },

    {
      id: "nothing3",
      name: "Nothing Phone 3",
      brand: "Nothing",
      price: 49999,
      rating: 4.4,
      image: "/products/nothing3.jpg",
      category: "mobile",
      battery: "5000mAh",
      camera: "50MP Dual Camera",
      display: "6.7 inch AMOLED",
      processor: "Snapdragon 8s Gen 4",
    },

    {
      id: "macbookairm4",
      name: "MacBook Air M4",
      brand: "Apple",
      price: 114999,
      rating: 4.8,
      image: "/products/macbookairm4.jpg",
      category: "laptop",
      battery: "18 Hours",
      camera: "12MP Center Stage",
      display: "13.6 inch Liquid Retina",
      processor: "Apple M4",
    },

    {
      id: "asusrog",
      name: "ASUS ROG Zephyrus G16",
      brand: "ASUS",
      price: 169999,
      rating: 4.7,
      image: "/products/asusrog.jpg",
      category: "laptop",
      battery: "90Wh",
      camera: "1080p",
      display: "16 inch OLED 240Hz",
      processor: "Intel Core Ultra 9",
    },

    {
      id: "lenovolegion",
      name: "Lenovo Legion 7i",
      brand: "Lenovo",
      price: 159999,
      rating: 4.6,
      image: "/products/lenovolegion.jpg",
      category: "laptop",
      battery: "99Wh",
      camera: "1080p",
      display: "16 inch QHD+ 240Hz",
      processor: "Intel Core i9",
    },

    {
      id: "dellxps14",
      name: "Dell XPS 14",
      brand: "Dell",
      price: 149999,
      rating: 4.5,
      image: "/products/dellxps14.jpg",
      category: "laptop",
      battery: "70Wh",
      camera: "1080p",
      display: "14.5 inch OLED",
      processor: "Intel Core Ultra 7",
    },
     
    {
      id: "iphone16",
      name: "iPhone 16",
      brand: "Apple",
      price: 89999,
      rating: 4.8,
      image: "/products/iphone16.jpg",
      category: "mobile",
      battery: "3561mAh",
      camera: "48MP",
      display: "6.1 inch OLED",
      processor: "A18",
    },

    {
      id: "iphone16pro",
      name: "iPhone 16 Pro",
      brand: "Apple",
      price: 129999,
      rating: 4.9,
      image: "/products/iphone16pro.jpg",
      category: "mobile",
      battery: "3582mAh",
      camera: "48MP Triple Camera",
      display: "6.3 inch OLED",
      processor: "A18 Pro",
      },

      {
      id: "galaxys25",
      name: "Samsung Galaxy S25",
      brand: "Samsung",
      price: 79999,
      rating: 4.7,
      image: "/products/galaxys25.jpg",
      category: "mobile",
      battery: "4200mAh",
      camera: "50MP",
      display: "6.2 inch AMOLED",
      processor: "Snapdragon 8 Elite",
      },

      {
      id: "galaxys25ultra",
      name: "Samsung Galaxy S25 Ultra",
      brand: "Samsung",
      price: 134999,
      rating: 4.9,
      image: "/products/galaxys25ultra.jpg",
      category: "mobile",
      battery: "5000mAh",
      camera: "200MP",
      display: "6.9 inch AMOLED",
      processor: "Snapdragon 8 Elite",
      },

      {
      id: "oneplus12",
      name: "OnePlus 12",
      brand: "OnePlus",
      price: 59999,
      rating: 4.7,
      image: "/products/oneplus12.jpg",
      category: "mobile",
      battery: "5400mAh",
      camera: "50MP",
      display: "6.82 inch AMOLED",
      processor: "Snapdragon 8 Gen 3",
      },

      {
      id: "xiaomi15",
      name: "Xiaomi 15",
      brand: "Xiaomi",
      price: 64999,
      rating: 4.6,
      image: "/products/xiaomi15.jpg",
      category: "mobile",
      battery: "5400mAh",
      camera: "50MP Leica",
      display: "6.36 inch AMOLED",
      processor: "Snapdragon 8 Elite",
      },

      {
      id: "realmegt7",
      name: "Realme GT 7",
      brand: "Realme",
      price: 42999,
      rating: 4.5,
      image: "/products/realmgtT7.jpg",
      category: "mobile",
      battery: "7000mAh",
      camera: "50MP",
      display: "6.78 inch AMOLED",
      processor: "Dimensity 9400",
      },

      {
      id: "iqoo13",
      name: "iQOO 13",
      brand: "iQOO",
      price: 54999,
      rating: 4.6,
      image: "/products/iqoo13.jpg",
      category: "mobile",
      battery: "6000mAh",
      camera: "50MP Triple Camera",
      display: "6.82 inch AMOLED",
      processor: "Snapdragon 8 Elite",
      },

      {
      id: "vivox200",
      name: "Vivo X200",
      brand: "Vivo",
      price: 69999,
      rating: 4.7,
      image: "/products/vivox200.jpg",
      category: "mobile",
      battery: "5800mAh",
      camera: "50MP Zeiss",
      display: "6.67 inch AMOLED",
      processor: "Dimensity 9400",
      },

   {
      id: "oppofindx8",
      name: "Oppo Find X8",
      brand: "Oppo",
      price: 69999,
      rating: 4.6,
      image: "/products/oppofindx8.jpg",
      category: "mobile",
      battery: "5600mAh",
      camera: "50MP Hasselblad",
      display: "6.59 inch AMOLED",
      processor: "Dimensity 9400",
   },

   {
      id: "hpomen",
      name: "HP Omen 16",
      brand: "HP",
      price: 129999,
      rating: 4.4,
      image: "/products/hpomen.jpg",
      category: "laptop",
      battery: "83Wh",
      camera: "1080p",
      display: "16.1 inch QHD 240Hz",
      processor: "Ryzen 9",
    }
  ]);
}
